-- ============================================================================
-- mod-arac UNINSTALL SQL
-- Reverts the changes made by mod-arac (All Races All Classes) to acore_world.
-- Applies to this Docker setup: run against the acore_world database, then
-- restore the stock DBC files and restart ac-worldserver (see mod-arac-notes.md).
--
-- Usage:
--   docker exec -i ac-database mysql --user=root --password=password acore_world < mod-arac-uninstall.sql
-- ============================================================================

-- 1) player_totem_model: remove the 20 totem rows ARAC added for
--    Human/NightElf/Undead/Gnome/BloodElf (races 1,4,5,7,10).
--    (Stock had no totem rows for these races.)
DELETE FROM `player_totem_model` WHERE RaceID IN (1,4,5,7,10);

-- 2) playercreateinfo: remove the 38 non-stock race/class rows ARAC added.
DELETE FROM `playercreateinfo` WHERE race = 1 AND class = 3;
DELETE FROM `playercreateinfo` WHERE race = 1 AND class = 7;
DELETE FROM `playercreateinfo` WHERE race = 1 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 2 AND class = 2;
DELETE FROM `playercreateinfo` WHERE race = 2 AND class = 5;
DELETE FROM `playercreateinfo` WHERE race = 2 AND class = 8;
DELETE FROM `playercreateinfo` WHERE race = 2 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 3 AND class = 7;
DELETE FROM `playercreateinfo` WHERE race = 3 AND class = 8;
DELETE FROM `playercreateinfo` WHERE race = 3 AND class = 9;
DELETE FROM `playercreateinfo` WHERE race = 3 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 4 AND class = 2;
DELETE FROM `playercreateinfo` WHERE race = 4 AND class = 7;
DELETE FROM `playercreateinfo` WHERE race = 4 AND class = 8;
DELETE FROM `playercreateinfo` WHERE race = 4 AND class = 9;
DELETE FROM `playercreateinfo` WHERE race = 5 AND class = 2;
DELETE FROM `playercreateinfo` WHERE race = 5 AND class = 3;
DELETE FROM `playercreateinfo` WHERE race = 5 AND class = 7;
DELETE FROM `playercreateinfo` WHERE race = 5 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 6 AND class = 2;
DELETE FROM `playercreateinfo` WHERE race = 6 AND class = 4;
DELETE FROM `playercreateinfo` WHERE race = 6 AND class = 5;
DELETE FROM `playercreateinfo` WHERE race = 6 AND class = 8;
DELETE FROM `playercreateinfo` WHERE race = 6 AND class = 9;
DELETE FROM `playercreateinfo` WHERE race = 7 AND class = 2;
DELETE FROM `playercreateinfo` WHERE race = 7 AND class = 3;
DELETE FROM `playercreateinfo` WHERE race = 7 AND class = 5;
DELETE FROM `playercreateinfo` WHERE race = 7 AND class = 7;
DELETE FROM `playercreateinfo` WHERE race = 7 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 8 AND class = 2;
DELETE FROM `playercreateinfo` WHERE race = 8 AND class = 9;
DELETE FROM `playercreateinfo` WHERE race = 8 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 10 AND class = 1;
DELETE FROM `playercreateinfo` WHERE race = 10 AND class = 7;
DELETE FROM `playercreateinfo` WHERE race = 10 AND class = 11;
DELETE FROM `playercreateinfo` WHERE race = 11 AND class = 4;
DELETE FROM `playercreateinfo` WHERE race = 11 AND class = 9;
DELETE FROM `playercreateinfo` WHERE race = 11 AND class = 11;

-- 3) playercreateinfo_action: remove the action rows ARAC added.
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 1 AND button = 82;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 3 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 3 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 3 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 3 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 7 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 7 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 7 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 7 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 1 AND class = 11 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 2 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 2 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 2 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 2 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 5 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 5 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 5 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 8 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 8 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 8 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 73;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 76;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 85;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 97;
DELETE FROM `playercreateinfo_action` WHERE race = 2 AND class = 11 AND button = 109;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 1 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 3 AND button = 75;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 3 AND button = 76;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 7 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 7 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 7 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 7 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 7 AND button = 4;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 8 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 8 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 8 AND button = 10;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 8 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 9 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 9 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 9 AND button = 10;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 9 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 11 AND button = 10;
DELETE FROM `playercreateinfo_action` WHERE race = 3 AND class = 11 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 1 AND button = 82;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 1 AND button = 85;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 1 AND button = 97;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 1 AND button = 109;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 2 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 2 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 2 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 2 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 3 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 4 AND button = 82;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 6 AND button = 83;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 7 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 7 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 7 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 7 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 8 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 8 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 8 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 9 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 9 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 4 AND class = 9 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 2 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 2 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 2 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 2 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 3 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 3 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 3 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 3 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 7 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 7 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 7 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 7 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 5 AND class = 11 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 1 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 1 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 2 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 2 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 2 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 2 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 3 AND button = 76;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 4 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 4 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 4 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 4 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 4 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 5 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 5 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 5 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 6 AND button = 75;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 7 AND button = 76;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 8 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 8 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 8 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 9 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 9 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 9 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 11 AND button = 73;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 11 AND button = 76;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 11 AND button = 85;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 11 AND button = 97;
DELETE FROM `playercreateinfo_action` WHERE race = 6 AND class = 11 AND button = 109;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 82;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 2 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 2 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 2 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 2 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 3 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 3 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 3 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 3 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 5 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 5 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 5 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 6 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 6 AND button = 72;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 6 AND button = 83;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 6 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 6 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 6 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 7 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 7 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 7 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 7 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 7 AND class = 11 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 1 AND button = 75;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 2 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 2 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 2 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 2 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 9 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 9 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 9 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 8 AND class = 11 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 72;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 73;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 82;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 7 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 7 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 7 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 7 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 10 AND class = 11 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 1 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 1 AND button = 84;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 1 AND button = 96;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 1 AND button = 108;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 3 AND button = 72;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 3 AND button = 73;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 3 AND button = 74;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 4 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 4 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 4 AND button = 2;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 4 AND button = 3;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 4 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 6 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 9 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 9 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 9 AND button = 11;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 11 AND button = 0;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 11 AND button = 1;
DELETE FROM `playercreateinfo_action` WHERE race = 11 AND class = 11 AND button = 11;

-- 4) playercreateinfo_spell_custom: stock table was empty, remove all ARAC rows.
DELETE FROM `playercreateinfo_spell_custom`;

-- 5) playercreateinfo_skills: restore original raceMask for the weapon skills
--    ARAC zeroed out.
UPDATE `playercreateinfo_skills` SET raceMask = 650 WHERE raceMask = 0 AND classMask = 4 AND skill = 45;
UPDATE `playercreateinfo_skills` SET raceMask = 36 WHERE raceMask = 0 AND classMask = 4 AND skill = 46;
UPDATE `playercreateinfo_skills` SET raceMask = 32 WHERE raceMask = 0 AND classMask = 1 AND skill = 160;
UPDATE `playercreateinfo_skills` SET raceMask = 200 WHERE raceMask = 0 AND classMask = 1 AND skill = 173;
UPDATE `playercreateinfo_skills` SET raceMask = 520 WHERE raceMask = 0 AND classMask = 4 AND skill = 173;
UPDATE `playercreateinfo_skills` SET raceMask = 8 WHERE raceMask = 0 AND classMask = 1024 AND skill = 173;
UPDATE `playercreateinfo_skills` SET raceMask = 1024 WHERE raceMask = 0 AND classMask = 4 AND skill = 226;

-- 6) quest_template: restore original AllowableRaces for the quests ARAC
--    broadened to all races.
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 26;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 27;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 28;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 29;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 30;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 31;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 63;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 96;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 100;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 220;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 272;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 397;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 792;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1103;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1442;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1462;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1463;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1464;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1470;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 1471;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1472;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 1473;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1474;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1476;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 1478;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1485;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1498;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 1499;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 1501;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1502;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1503;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 1504;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1505;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 1506;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1507;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1508;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1509;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1510;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1511;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1512;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1513;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1515;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 1516;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 1517;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 1518;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 1519;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 1520;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 1521;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1522;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1523;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1524;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1525;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1526;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1527;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1528;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1529;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1530;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1531;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1532;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1534;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1535;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1536;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1598;
UPDATE `quest_template` SET AllowableRaces = 64 WHERE id = 1599;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1638;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1639;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1640;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1641;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1642;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1643;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1644;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1645;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1646;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1647;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1648;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1649;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1650;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1651;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1652;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1653;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1654;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1655;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1661;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1665;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1666;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1667;
UPDATE `quest_template` SET AllowableRaces = 68 WHERE id = 1678;
UPDATE `quest_template` SET AllowableRaces = 68 WHERE id = 1679;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1680;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1681;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1682;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1683;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1684;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1685;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1686;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1688;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1689;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1692;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1693;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1698;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1699;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1700;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1701;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1702;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 1703;
UPDATE `quest_template` SET AllowableRaces = 68 WHERE id = 1704;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1705;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1706;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1708;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1709;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1710;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1711;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1715;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1716;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1717;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1738;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1739;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1758;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1778;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1779;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1780;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1781;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1783;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1784;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1785;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1786;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1787;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1788;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 1789;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1790;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1793;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1794;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1798;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1801;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1802;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1803;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1804;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1805;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1806;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1818;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1819;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1820;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1821;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1822;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1823;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1824;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1825;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1838;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1839;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1840;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1841;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1842;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1843;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1844;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1845;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1846;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1847;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1848;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1858;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1859;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1860;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 1861;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1879;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1880;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1881;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1882;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1883;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1884;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1885;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1886;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1898;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1899;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1919;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1920;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1921;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1938;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1939;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1940;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1941;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 1942;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1943;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1944;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1945;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1946;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1959;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1960;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1961;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1962;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1963;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1978;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1998;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 1999;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2205;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2206;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2218;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2238;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2239;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2241;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2242;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2259;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2260;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2281;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2282;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2298;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2299;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2300;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2359;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2360;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2378;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2379;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2380;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2381;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2382;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 2383;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2458;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2460;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2478;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2479;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2480;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2607;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2608;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 2609;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2983;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2984;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2985;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 2996;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 2997;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 2998;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 2999;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 3000;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 3001;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 3065;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 3082;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 3083;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 3084;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 3085;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 3086;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 3087;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 3088;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 3089;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 3090;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 3091;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 3092;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 3093;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 3094;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3100;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3101;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3102;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3103;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3104;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3105;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 3106;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 3107;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 3108;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 3109;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 3110;
UPDATE `quest_template` SET AllowableRaces = 64 WHERE id = 3112;
UPDATE `quest_template` SET AllowableRaces = 64 WHERE id = 3113;
UPDATE `quest_template` SET AllowableRaces = 64 WHERE id = 3114;
UPDATE `quest_template` SET AllowableRaces = 64 WHERE id = 3115;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 3116;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 3117;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 3118;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 3119;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 3120;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 3631;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 3681;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4485;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4486;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4487;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4488;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 4489;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4736;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 4737;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4738;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 4739;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4965;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 4967;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 4969;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5061;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5621;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5622;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 5623;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 5624;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 5625;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 5626;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5627;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5628;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5629;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5630;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5631;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5632;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5633;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5634;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5635;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5636;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5637;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5638;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5639;
UPDATE `quest_template` SET AllowableRaces = 5 WHERE id = 5640;
UPDATE `quest_template` SET AllowableRaces = 1028 WHERE id = 5641;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5642;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5643;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5644;
UPDATE `quest_template` SET AllowableRaces = 1028 WHERE id = 5645;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5646;
UPDATE `quest_template` SET AllowableRaces = 1028 WHERE id = 5647;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 5648;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 5649;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 5650;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 5651;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5652;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5654;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5655;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5656;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5657;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5658;
UPDATE `quest_template` SET AllowableRaces = 144 WHERE id = 5659;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5660;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5661;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5662;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5663;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5672;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5673;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5674;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5675;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 5676;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 5677;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 5678;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 5679;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 5680;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5921;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 5922;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5923;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5924;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5925;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 5926;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 5927;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 5928;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5929;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 5930;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 5931;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 5932;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6001;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6002;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6061;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6062;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6063;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6064;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6065;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6066;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6067;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6068;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6069;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6070;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6071;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6072;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6073;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6074;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6075;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6076;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6081;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6082;
UPDATE `quest_template` SET AllowableRaces = 130 WHERE id = 6083;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6084;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6085;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 6086;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6087;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6088;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 6089;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6101;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6102;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6103;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 6121;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 6122;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 6123;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 6124;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 6125;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 6126;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 6127;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 6128;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 6129;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 6130;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6721;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 6722;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7562;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7563;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7564;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7623;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7624;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7625;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7626;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7627;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7628;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7629;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7630;
UPDATE `quest_template` SET AllowableRaces = 595 WHERE id = 7631;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7637;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7638;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7639;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7640;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7641;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7642;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7643;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7644;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7645;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7646;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7647;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 7648;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 7666;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 7667;
UPDATE `quest_template` SET AllowableRaces = 1029 WHERE id = 7670;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8258;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 8328;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8344;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8414;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8415;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8416;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8418;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 8563;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 8564;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8905;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8906;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8907;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8908;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8909;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8910;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8911;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8912;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8913;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8914;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8915;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8916;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8917;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8918;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8919;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8920;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8926;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8927;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8931;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8932;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8933;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8934;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8935;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8936;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8937;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8938;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8939;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8940;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8941;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8942;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8943;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8944;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8951;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8952;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8953;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8954;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8955;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8956;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 8957;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8958;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8959;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 8999;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9000;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9001;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9002;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9003;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9004;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9005;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9006;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9007;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9008;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9009;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9010;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9011;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9012;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9013;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9014;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9016;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9017;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9018;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9019;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9020;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9021;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9022;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9287;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9288;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9290;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9291;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9392;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9393;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9402;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9403;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9404;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9421;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9449;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9450;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9451;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9460;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9462;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9464;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9465;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9467;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9468;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9484;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9485;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9486;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9488;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9489;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9491;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9500;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9501;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9503;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9504;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9508;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9509;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9529;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9532;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9547;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9551;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9552;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9553;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9554;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9555;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9582;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9586;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9591;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9592;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9593;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 9595;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9598;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9600;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9601;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9617;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 9618;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9619;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9673;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9675;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9676;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9677;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9678;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9681;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9684;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9685;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9686;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9690;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9691;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9692;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9707;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9710;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9712;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9721;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9722;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9723;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9735;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9736;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 9737;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 9757;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10068;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10069;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10070;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10071;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10072;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10073;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 10350;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 10366;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10372;
UPDATE `quest_template` SET AllowableRaces = 1028 WHERE id = 10377;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 10490;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 10491;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 10492;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10493;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 10494;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10495;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 10496;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10497;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 10498;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10499;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10530;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10548;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10590;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10592;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10593;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 10779;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 10788;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 10789;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 10790;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 10794;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 12172;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 12173;
UPDATE `quest_template` SET AllowableRaces = 32 WHERE id = 12739;
UPDATE `quest_template` SET AllowableRaces = 1 WHERE id = 12742;
UPDATE `quest_template` SET AllowableRaces = 8 WHERE id = 12743;
UPDATE `quest_template` SET AllowableRaces = 4 WHERE id = 12744;
UPDATE `quest_template` SET AllowableRaces = 64 WHERE id = 12745;
UPDATE `quest_template` SET AllowableRaces = 1024 WHERE id = 12746;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 12747;
UPDATE `quest_template` SET AllowableRaces = 2 WHERE id = 12748;
UPDATE `quest_template` SET AllowableRaces = 128 WHERE id = 12749;
UPDATE `quest_template` SET AllowableRaces = 16 WHERE id = 12750;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13188;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13189;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13410;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13411;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13682;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13788;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13789;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13790;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13791;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13793;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13809;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13810;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13811;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13812;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13813;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13814;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13861;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13862;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 13863;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 13864;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 14418;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 14419;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 14420;
UPDATE `quest_template` SET AllowableRaces = 690 WHERE id = 14421;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 24553;
UPDATE `quest_template` SET AllowableRaces = 178 WHERE id = 24564;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 24594;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 24595;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 24596;
UPDATE `quest_template` SET AllowableRaces = 178 WHERE id = 24598;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 24795;
UPDATE `quest_template` SET AllowableRaces = 1101 WHERE id = 24796;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 24798;
UPDATE `quest_template` SET AllowableRaces = 178 WHERE id = 24799;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 24800;
UPDATE `quest_template` SET AllowableRaces = 178 WHERE id = 24801;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 109681;
UPDATE `quest_template` SET AllowableRaces = 512 WHERE id = 109684;

-- ============================================================================
-- Done. Now restore the stock DBC files and restart worldserver (see notes).
-- ============================================================================
